"""rename address

Revision ID: 6c954d3ee6a5
Revises: c79fc211843d
Create Date: 2024-04-04 09:20:36.909883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c954d3ee6a5'
down_revision = 'c79fc211843d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name= 'address')

    # ### end Alembic commands ###
